# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='fav_numx',
            new_name='fav_nums',
        ),
    ]
